spring:
  redis:
    database: 0
    host: 192.168.127.134
    port: 7000
    timeout: 1000

    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 3000
        min-idle: 1

  datasource:
    username: vsinger
    password: vsinger
    url: jdbc:mysql://localhost:3306/vsinger?serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8989